{
 "title": "{{ data_source }}",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"tmp_cpu_sar\" WITH KEY = \"host\""
   },
   { "name": "aggregation", "label": "Aggregation Interval", "query": "1,10,30,60,600,1800,3600" },
   {
    "name": "label",
    "label": "Requests",
    "query": "SHOW TAG VALUES FROM \"tmp_samples_jmeter\" WITH KEY = \"label\" "
   },
   {
    "name": "IFACE",
    "label": "Card Iterface Name (Network_measures)",
    "query": "SHOW TAG VALUES FROM \"tmp_network_sar\" WITH KEY = \"IFACE\""
   },
   {
    "name": "version",
    "label": "Version",
    "query": "SHOW TAG VALUES FROM \"tmp_samples_jmeter\" WITH KEY = \"version\""
   },
   {
    "name": "module",
    "label": "Module",
    "query": "SHOW TAG VALUES FROM \"tmp_samples_jmeter\" WITH KEY = \"module\""
   }
  ]
 },
 "panels": [
  {
   "title": "JMETER RESULTS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Elapsed time (ms)" }
   ],
   "targets": [
    {
     "alias": "%Number of threads $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "tmp_samples_jmeter",
     "query": "SELECT mean(\"grpThreads\") FROM \"tmp_samples_jmeter\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "grpThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_label $tag_module $tag_version vs elapsed time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"elapsed\") FROM \"tmp_samples_jmeter\" WHERE \"label\" =~ /^$label$/ AND \"sentBytes\" >= 0  AND \"version\" =~ /^$version$/ AND \"module\" =~ /^$module$/ AND $timeFilter GROUP BY time($__interval), \"label\",  \"module\", \"version\"  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active memory vs Number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Number of threads" }
   ],
   "targets": [
    {
     "alias": "Active memory (kb active) $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tmp_memory_sar",
     "query": "SELECT mean(\"kbactive\") FROM \"tmp_memory_sar\" WHERE (\"host\" =~ /^$host$/ AND \"module\" =~ /^$module$/ AND \"version\" =~ /^$version$/) AND $timeFilter GROUP BY time($__interval) ,  \"module\", \"version\"  fill(linear)",
     "select": [
      [
       { "params": [ "kbactive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%Number of threads $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "tmp_samples_jmeter",
     "select": [
      [
       { "params": [ "grpThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  {
   "title": " Active cpu vs Number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "%Active cpu" }
   ],
   "targets": [
    {
     "alias": "%Number of threads $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "tmp_samples_jmeter",
     "select": [
      [
       { "params": [ "grpThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%Active cpu $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tmp_cpu_sar",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  { "title": "Another metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory distribution vs Number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "kbactive $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tmp_memory_sar",
     "select": [
      [
       { "params": [ "kbactive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "kbcached $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tmp_memory_sar",
     "select": [
      [
       { "params": [ "kbcached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "kbdirty $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tmp_memory_sar",
     "select": [
      [
       { "params": [ "kbdirty" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "kbinact $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tmp_memory_sar",
     "select": [
      [
       { "params": [ "kbinact" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "kbmemfree $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tmp_memory_sar",
     "select": [
      [
       { "params": [ "kbmemfree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "kbbuffers $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tmp_memory_sar",
     "select": [
      [
       { "params": [ "kbbuffers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%Number of threads $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "tmp_samples_jmeter",
     "select": [
      [
       { "params": [ "grpThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  {
   "title": "%Memory used vs Number of threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent", "label": "% Memory used" }
   ],
   "targets": [
    {
     "alias": "%memused $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "tmp_memory_sar",
     "select": [
      [
       { "params": [ "%memused" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%Number of threads $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "tmp_samples_jmeter",
     "select": [
      [
       { "params": [ "grpThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage vs Number of threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "%system $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp_cpu_sar",
     "select": [
      [
       { "params": [ "%system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%idle $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp_cpu_sar",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%steal $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp_cpu_sar",
     "select": [
      [
       { "params": [ "%steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%iowait $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp_cpu_sar",
     "select": [
      [
       { "params": [ "%iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%nice $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp_cpu_sar",
     "select": [
      [
       { "params": [ "%nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%user $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp_cpu_sar",
     "select": [
      [
       { "params": [ "%user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "%Number of threads $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" }
     ],
     "measurement": "tmp_samples_jmeter",
     "select": [
      [
       { "params": [ "grpThreads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk measures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "bread/s (Bytes read per second) $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" }
     ],
     "measurement": "tmp_disk_sar",
     "query": "SELECT mean(\"bread/s\") FROM \"tmp_disk_sar\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "bread/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "bwrtn/s (Bytes written per second) $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" }
     ],
     "measurement": "tmp_disk_sar",
     "query": "SELECT mean(\"bwrtn/s\") FROM \"tmp_disk_sar\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "bwrtn/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "tps (Transactions per second, this includes both read and write) $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" }
     ],
     "measurement": "tmp_disk_sar",
     "query": "SELECT mean(\"tps\") FROM \"tmp_disk_sar\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "tps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "rtps (Read transactions per second) $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" }
     ],
     "measurement": "tmp_disk_sar",
     "query": "SELECT mean(\"rtps\") FROM \"tmp_disk_sar\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "rtps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "wtps (Write transactions per second) $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" }
     ],
     "measurement": "tmp_disk_sar",
     "query": "SELECT mean(\"wtps\") FROM \"tmp_disk_sar\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "wtps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  {
   "title": "Network measures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_IFACE %ifutil $tag_module $tag_version",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"%ifutil\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "%ifutil" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_IFACE rxcmp/s $tag_module $tag_version",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"rxcmp/s\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "rxcmp/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_IFACE rxkB/s  $tag_module $tag_version",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"rxkB/s\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "rxkB/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_IFACE  rxmcst/s $tag_module $tag_version",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"rxmcst/s\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "rxmcst/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_IFACE rxkB/s $tag_module $tag_version",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"rxkB/s\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "rxkB/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_IFACE rxmcst/s $tag_module $tag_version",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"rxmcst/s\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "rxmcst/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_IFACE  rxpck/s $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"rxpck/s\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "rxpck/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_IFACE txcmp/s $tag_module $tag_version",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"txcmp/s\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "txcmp/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_IFACE  txkB/s $tag_module $tag_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"txkB/s\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "txkB/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    },
    {
     "alias": "$tag_IFACE txpck/s $tag_module $tag_version",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "IFACE" ], "type": "tag" },
      { "params": [ "module" ], "type": "tag" },
      { "params": [ "version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp_network_sar",
     "query": "SELECT mean(\"txpck/s\") FROM \"tmp_network_sar\" WHERE (\"host\" =~ /^$host$/ AND \"IFACE\" =~ /^$IFACE$/) AND $timeFilter GROUP BY time($__interval), \"IFACE\" fill(null)",
     "select": [
      [
       { "params": [ "txpck/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "IFACE", "operator": "=~", "value": "/^$IFACE$/" },
      { "condition": "AND", "key": "module", "operator": "=~", "value": "/^$module$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  }
 ]
}