version: '3'

services:
  master:
    build: injectors/
    ports:
     - "8089:8089"
    volumes:
     - $HOME_PATH:/mnt/performance
    environment:
     - SAMPLING=$SAMPLING
    command: -f /mnt/performance/scenarios/$TEST --master -H https://blazedemo.com/ --tags $TAGS
  
  worker:
    build: injectors/
    volumes:
     - $HOME_PATH:/mnt/performance
    environment:
     - SAMPLING=$SAMPLING
    command: -f /mnt/performance/scenarios/$TEST --worker --master-host master --tags $TAGS
