services:
  locustWorker:
    image: locustio/locust:2.15.1
    volumes:
      - /home/adminuser/locust/scenarios:/mnt/locust
    environment:
      - LOCUST_MODE=worker
    command: -f /mnt/locust/locustfile.py --worker --master-host=locustMaster-vm
  locustMaster:
    image: locustio/locust:2.15.1
    ports:
      - 8089:8089
      - 5557:5557
    volumes:
      - /home/adminuser/locust/scenarios:/mnt/locust
    environment:
      - LOCUST_MODE=master
    command: -f /mnt/locust/locustfile.py --master
