name: Run parse-costs script

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  run-parse-costs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r reporter/requirements.txt

      - name: Run parse-costs script for all subscriptions
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

        run: |
          python3 reporter/parse-costs.py 1
